# run with `docker-compose up -d`
version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16  # Postgres 16 with pgvector installed
    container_name: video-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
